name: check
on: pull_request
jobs:
    prepare-env:
        runs-on:
            group: infra1-runners-arc
            labels: runners-small
        outputs:
            branch: ${{ github.base_ref }}
            ref: ${{ github.ref }}
            commit: ${{ github.event.pull_request.head.sha }}
            pr_number: ${{ github.event.pull_request.number }}
            project: ${{ github.repository }}
            changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v40
    gooddata-react-components-unit-tests-zuul-docker:
        runs-on:
            group: infra1-runners-arc
            labels: runners-small
        needs:
            - prepare-env
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Call Jenkins trigger
              id: call-jenkins
              uses: gooddata/github-actions-public/jenkins/trigger@master
              with:
                  server: ${{ env.JENKINS_ADDRESS }}
                  folder: client-libs
                  job-name: gooddata-react-components-unit-tests-zuul-docker
                  vault-url: ${{ env.VAULT_ADDRESS }}
                  params: |-
                      {
                        "GH_BRANCH": "${{ needs.prepare-env.outputs.branch }}",
                        "GH_REF": "${{ needs.prepare-env.outputs.ref }}",
                        "GH_COMMIT": "${{ needs.prepare-env.outputs.commit }}",
                        "GH_URL": "git@github.com:",
                        "GH_CHANGE": "${{ needs.prepare-env.outputs.pr_number }}",
                        "GH_PROJECT": "${{ needs.prepare-env.outputs.project }}",
                        "BUILD_BY_GITHUB": "true",
                        "GH_PIPELINE": "check"
                      }
                  comment-pr: "true"
    gooddata-react-components-fossa-licenses-validate-LR-ticket-zuul:
        runs-on:
            group: infra1-runners-arc
            labels: runners-small
        needs:
            - prepare-env
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Check if any matching file changed
              id: changed-files
              run: |
                  any_changed=false
                  patterns=('^NOTICE(S)?(.TXT)?$' '^LICENSE(S)?(.TXT)?$')
                  for file in ${{ needs.prepare-env.outputs.changed_files }}; do
                      for pattern in "${patterns[@]}"; do
                          if [[ $file =~ $pattern ]]; then
                              any_changed=true
                          fi
                      done
                  done
                  echo "any_changed=$any_changed" >> "$GITHUB_OUTPUT"
            - name: Call Jenkins trigger
              id: call-jenkins
              uses: gooddata/github-actions-public/jenkins/trigger@master
              with:
                  server: ${{ env.JENKINS_ADDRESS }}
                  folder: compliance
                  job-name: gooddata-react-components-fossa-licenses-validate-LR-ticket-zuul
                  vault-url: ${{ env.VAULT_ADDRESS }}
                  params: |-
                      {
                        "GH_BRANCH": "${{ needs.prepare-env.outputs.branch }}",
                        "GH_REF": "${{ needs.prepare-env.outputs.ref }}",
                        "GH_COMMIT": "${{ needs.prepare-env.outputs.commit }}",
                        "GH_URL": "git@github.com:",
                        "GH_CHANGE": "${{ needs.prepare-env.outputs.pr_number }}",
                        "GH_PROJECT": "${{ needs.prepare-env.outputs.project }}",
                        "BUILD_BY_GITHUB": "true",
                        "GH_PIPELINE": "check"
                      }
                  comment-pr: "true"
              if: steps.changed-files.outputs.any_changed == 'true'
    ready-to-merge:
        runs-on:
            group: infra1-runners-arc
            labels: runners-small
        if: always()
        needs:
            - prepare-env
            - gooddata-react-components-unit-tests-zuul-docker
            - gooddata-react-components-fossa-licenses-validate-LR-ticket-zuul
        steps:
            - name: Check if needed jobs succeeded
              uses: re-actors/alls-green@release/v1
              with:
                  allowed-skips: ${{ toJSON(needs) }}
                  jobs: ${{ toJSON(needs) }}
